---
stages:
  - build-containers
  - test
  - release

include:
  - project: 'connylegal/mietright_deployments'
    ref: main
    file: '/.gitlab-ci/build-container.yaml'
  - project: 'connylegal/mietright_deployments'
    ref: main
    file: '/.gitlab-ci/deploy.yaml'

variables:
  FAILFASTCI_NAMESPACE: connylegal
  OCI_REPO: img.conny.dev
  IMAGE_NAME: $OCI_REPO/conny/meowlflow

build-container:
  extends: .build-container
  stage: build-containers

diff:
  tags:
    - kubernetes
  stage: test
  needs: []
  image:
    name: python:3.9
    entrypoint: ['']
  script:
    - make README.md -B
    - |
        DIFF="$(git status --porcelain 2>/dev/null )"
        if [ "$(echo -n "$DIFF" | wc -l)" -ne 0 ]; then
          printf 'README.md is out of date!\nDiff:\n%s\nRun:\n\tmake README.md\n' "$DIFF"
          exit 1
        fi

lint:
  tags:
    - kubernetes
  stage: test
  needs: []
  image:
    name: python:3.9
    entrypoint: ['']
  script:
    - pip install poetry
    - poetry install
    - make flake8-test
    - make black-test

smoketest:
  tags:
    - kubernetes
  stage: test
  needs: []
  image:
    name: python:3.9
    entrypoint: ['']
  script:
    - pip install .
    - python -c "from meowlflow.serve import app"

openapi:
  tags:
    - kubernetes
  stage: test
  needs: []
  image:
    name: python:3.9
    entrypoint: ['']
  script:
    - pip install poetry
    - poetry install
    - diff examples/document_splitter_schema.json <(poetry run meowlflow openapi --schema-path=examples/document_splitter_schema.py 2>/dev/null)

tag image:
  needs:
    - build-container
    - lint
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_TAG'
  tags:
    - kubernetes
  stage: release
  image:
    name: $OCI_REPO/conny-tools/crane-conny:latest
  script:
    - crane cp $IMAGE_NAME:$CI_COMMIT_SHORT_SHA $IMAGE_NAME:$CI_COMMIT_REF_SLUG
