sudo: false

env:
  - TOXENV=py27
  - TOXENV=flake8

install:
  - pip install -U tox
  - pip install -U coveralls
  - pip install -U codecov

cache:
  - pip

language: python
script: tox

after_success:
  - if [ "$TOXENV" == "py27" ] ; then coveralls ; fi
  - if [ "$TOXENV" == "py27" ] ; then codecov ; fi
