name: CI

on:
  push:
    branches: [ main ]
    tags:
      - "*"
  pull_request:
    branches: [ main ]
  schedule:
  - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docs
      run: |
        make README.md -B
        DIFF="$(git status --porcelain 2>/dev/null )"
        if [ "$(echo -n "$DIFF" | wc -l)" -ne 0 ]; then
          printf 'README.md is out of date!\nDiff:\n%s\nRun:\n\tmake README.md\n' "$DIFF"
          exit 1
        fi

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: poetry
    - name: Install dependencies
      run: poetry install
    - name: flake8
      run: make flake8
    - name: black
      run: make black-test

  smoke:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: poetry
    - name: Test
      run: |
        pip install .
        python -c "from meowlflow.serve import app"

  openapi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: poetry
    - name: Install dependencies
      run: poetry install
    - name: Test
      run: diff examples/document_splitter_schema.json <(poetry run meowlflow openapi --schema-path=examples/document_splitter_schema.py 2>/dev/null)

  types:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: poetry
    - name: Install dependencies
      run: poetry install
    - name: mypy
      run: poetry run mypy examples meowlflow

  container:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build container
      uses: docker/build-push-action@v2
      with:
        context: .

  push:
    if: github.event_name != 'pull_request'
    needs:
    - docs
    - lint
    - smoke
    - openapi
    - container
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Determine SHA
      id: sha
      run: echo "::set-output name=sha::$(git describe --always --tags --dirty)"
    - name: Build and push
      id: push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        platforms: linux/arm64, linux/amd64
        tags: ghcr.io/connylabs/meowlflow:latest, ghcr.io/connylabs/meowlflow:${{ steps.sha.outputs.sha }}
    - name: Determine digest
      run: echo ${{ steps.push.outputs.digest }}
